---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  pre_tasks:        
  roles:
    - role-base
  post_tasks:
  - name: Restart netdata
    systemd:
      name: netdata
      state: restarted
      enabled: true
